import React, { useState } from 'react';
import Head from 'next/head';
import DatePicker from 'react-datepicker';
import 'react-datepicker/dist/react-datepicker.css';
import axios from 'axios';

const Home = () => {
    const [selectedDate, setSelectedDate] = useState(null);
    const [brigadista, setBrigadista] = useState('');
    const [markType, setMarkType] = useState('');

    const handleDateChange = (date) => {
        setSelectedDate(date);
    };

    const handleSubmit = async (e) => {
        e.preventDefault();

        const formData = {
        brigadista: brigadista,
        date: selectedDate.toISOString().slice(0, 10),
        markType: markType,
        };

        try {
        const response = await axios.post('http://localhost:8000/api/asistencias', formData);
        console.log('Asistencia registrada:', response.data);
        // Aquí puedes manejar la respuesta del servidor o mostrar un mensaje de éxito
        } catch (error) {
        console.log('Error al registrar asistencia:', error);
        // Aquí puedes manejar el error o mostrar un mensaje de error
        }
    };

    return (
        <main className="d-flex flex-column min-vh-100">
        <Head>
            <title>Ingreso de asistencia</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
            rel="stylesheet"
            />
        </Head>
        <div className="px-4 py-5 my-5 text-center flex-grow-1">
            <div className="card mx-auto" style={{ maxWidth: '500px' }}>
            <div className="card-body">
                <h1 className="card-title display-5 fw-bold">Formulario de ingreso de asistencia</h1>
                <form onSubmit={handleSubmit}>
                <div className="mb-3">
                    <label htmlFor="brigadista" className="form-label fw-bold">
                    Brigadista
                    </label>
                    <input
                    type="text"
                    className="form-control"
                    id="brigadista"
                    placeholder="Ingrese el nombre del brigadista"
                    value={brigadista}
                    onChange={(e) => setBrigadista(e.target.value)}
                    required
                    />
                </div>
                <div className="mb-3">
                    <DatePicker
                    className="form-control"
                    id="fecha"
                    selected={selectedDate}
                    onChange={handleDateChange}
                    dateFormat="dd/MM/yyyy"
                    placeholderText="Seleccione una fecha"
                    required
                    />
                    <label htmlFor="fecha" className="form-label fw-bold mt-2">
                    Fecha
                    </label>
                </div>
                <div className="mb-3">
                    <label htmlFor="marca" className="form-label fw-bold">
                    Tipo de marca
                    </label>
                    <select
                    className="form-select"
                    id="marca"
                    value={markType}
                    onChange={(e) => setMarkType(e.target.value)}
                    required
                    >
                    <option value="">Seleccione una opción</option>
                    <option value="ENTRADA">Entrada</option>
                    <option value="SALIDA">Salida</option>
                    </select>
                </div>
                <button type="submit" className="btn btn-primary">
                    Registrar asistencia
                </button>
                </form>
                <a href="/brigada" className="btn btn-warning mt-3">
                Volver a asistencias
                </a>
            </div>
            </div>
        </div>
        </main>
    );
};

export default Home;
